// commands.ts
import * as vscode from 'vscode'
import * as logItem from '../types/log-item'

export const commandDescriptions = {
    // editCommands
    'editor.action.clipboardCutAction': { description: 'Cut Line (Empty Selection)', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.clipboardCopyAction': { description: 'Copy Line (Empty Selection)', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.deleteLines': { description: 'Delete Line', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.insertLineAfter': { description: 'Insert Line Below', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.insertLineBefore': { description: 'Insert Line Above', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.moveLinesDownAction': { description: 'Move Lines Down', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.moveLinesUpAction': { description: 'Move Lines Up', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.copyLinesDownAction': { description: 'Copy Line Down', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.copyLinesUpAction': { description: 'Copy Line Up', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.addSelectionToNextFindMatch': { description: 'Add Selection To Next Match', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.moveSelectionToNextFindMatch': { description: 'Move Selection To Next Match', artifactType: logItem.ArtifactType.MenuItem },
    'cursorUndo': { description: 'Undo', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.insertCursorAtEndOfEachLineSelected': { description: 'Insert Cursor At End Of Each Line', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.selectHighlights': { description: 'Select All Occurrences', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.changeAll': { description: 'Select All Occurrences', artifactType: logItem.ArtifactType.MenuItem },
    'expandLineSelection': { description: 'Expand Line Selection', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.insertCursorBelow': { description: 'Insert Cursor Below', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.insertCursorAbove': { description: 'Insert Cursor Above', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.jumpToBracket': { description: 'Jump To Bracket', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.indentLines': { description: 'Indent Line', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.outdentLines': { description: 'Outdent Line', artifactType: logItem.ArtifactType.MenuItem },
    'cursorHome': { description: 'Move to Line Start', artifactType: logItem.ArtifactType.MenuItem },
    'cursorEnd': { description: 'Move to Line End', artifactType: logItem.ArtifactType.MenuItem },
    'cursorBottom': { description: 'Move to File End', artifactType: logItem.ArtifactType.MenuItem },
    'cursorTop': { description: 'Move to File Start', artifactType: logItem.ArtifactType.MenuItem },
    'scrollLineDown': { description: 'Scroll Line Down', artifactType: logItem.ArtifactType.MenuItem },
    'scrollLineUp': { description: 'Scroll Line Up', artifactType: logItem.ArtifactType.MenuItem },
    'scrollPageDown': { description: 'Scroll Page Down', artifactType: logItem.ArtifactType.MenuItem },
    'scrollPageUp': { description: 'Scroll Page Up', artifactType: logItem.ArtifactType.MenuItem },
    'editor.fold': { description: 'Fold Region', artifactType: logItem.ArtifactType.MenuItem },
    'editor.unfoldRecursively': { description: 'Unfold Region', artifactType: logItem.ArtifactType.MenuItem },
    'editor.foldAll': { description: 'Fold All Regions', artifactType: logItem.ArtifactType.MenuItem },
    'editor.unfoldAll': { description: 'Unfold All Regions', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.addCommentLine': { description: 'Add Line Comment', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.removeCommentLine': { description: 'Remove Line Comment', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.commentLine': { description: 'Toggle Line Comment', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.blockComment': { description: 'Toggle Block Comment', artifactType: logItem.ArtifactType.MenuItem },
    'actions.find': { description: 'Find', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.startFindReplaceAction': { description: 'Replace', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.nextMatchFindAction': { description: 'Find Next', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.previousMatchFindAction': { description: 'Find Previous', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.selectAllMatches': { description: 'Select All Matches', artifactType: logItem.ArtifactType.MenuItem },
    'toggleFindCaseSensitive': { description: 'Toggle Find Case Sensitive', artifactType: logItem.ArtifactType.MenuItem },
    'toggleFindRegex': { description: 'Toggle Find Regex', artifactType: logItem.ArtifactType.MenuItem },
    'toggleFindWholeWord': { description: 'Toggle Find Whole Word', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.toggleTabFocusMode': { description: 'Toggle Tab Focus Mode', artifactType: logItem.ArtifactType.MenuItem },
    'toggleRenderWhitespace': { description: 'Toggle Render Whitespace', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.toggleWordWrap': { description: 'Toggle Word Wrap', artifactType: logItem.ArtifactType.MenuItem },
    // languageEditCommands
    'editor.action.triggerSuggest': { description: 'Trigger Suggestion', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.triggerParameterHints': { description: 'Trigger Parameter Hints', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.formatDocument': { description: 'Format Document', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.formatSelection': { description: 'Format Selection', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.revealDefinition': { description: 'Go to Definition', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.showHover': { description: 'Show Hover', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.peekDefinition': { description: 'Peek Definition', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.revealDefinitionAside': { description: 'Reveal Definition Aside', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.quickFix': { description: 'Quick Fix', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.referenceSearch.trigger': { description: 'Reference Search', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.rename': { description: 'Rename Symbol', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.inPlaceReplace.down': { description: 'Replace with Next Value', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.inPlaceReplace.up': { description: 'Replace with Previous Value', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.smartSelect.grow': { description: 'Expand AST Selection', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.smartSelect.shrink': { description: 'Shrink AST Selection', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.trimTrailingWhitespace': { description: 'Trim Trailing Whitespace', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.editor.changeLanguageMode': { description: 'Change Language Mode', artifactType: logItem.ArtifactType.MenuItem },
    // navigationCommand
    'workbench.action.showAllSymbols': { description: 'Show All Symbols', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.gotoLine': { description: 'Go to Line', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.quickOpen': { description: 'Quick Open', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.gotoSymbol': { description: 'Go to Symbol', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.actions.view.problems': { description: 'View Problems', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.marker.nextInFiles': { description: 'Next Error or Warning', artifactType: logItem.ArtifactType.MenuItem },
    'editor.action.marker.prevInFiles': { description: 'Previous Error or Warning', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.showCommands': { description: 'Show Commands',  artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.openPreviousRecentlyUsedEditorInGroup': { description: 'Open Previous Editor in Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.navigateBack': { description: 'Navigate Back', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.quickInputBack': { description: 'Quick Input Back', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.navigateForward': { description: 'Navigate Forward', artifactType: logItem.ArtifactType.MenuItem },
    // editorWindowCommand
    'workbench.action.newWindow': { description: 'New Window', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeWindow': { description: 'Close Window', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeActiveEditor': { description: 'Close Editor', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeFolder': { description: 'Close Folder', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.navigateEditorGroups': { description: 'Navigate Editor Groups', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.splitEditor': { description: 'Split Editor', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.focusFirstEditorGroup': { description: 'Focus First Editor Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.focusSecondEditorGroup': { description: 'Focus Second Editor Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.focusThirdEditorGroup': { description: 'Focus Third Editor Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.focusPreviousGroup': { description: 'Focus Previous Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.focusNextGroup': { description: 'Focus Next Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.moveEditorLeftInGroup': { description: 'Move Editor Left', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.moveEditorRightInGroup': { description: 'Move Editor Right', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.moveActiveEditorGroupLeft': { description: 'Move Active Editor Group Left', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.moveActiveEditorGroupRight': { description: 'Move Active Editor Group Right', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.moveEditorToNextGroup': { description: 'Move Editor to Next Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.moveEditorToPreviousGroup': { description: 'Move Editor to Previous Group', artifactType: logItem.ArtifactType.MenuItem },
    // fileManagementCommand
    'workbench.action.files.newUntitledFile': { description: 'New File', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.openFile': { description: 'Open File...', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.save': { description: 'Save', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.saveAll': { description: 'Save All', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.saveAs': { description: 'Save As...', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeOtherEditors': { description: 'Close Other Editors', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeEditorsInGroup': { description: 'Close Editors In Group', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeEditorsInOtherGroups': { description: 'Close Editors In Other Groups', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeEditorsToTheLeft': { description: 'Close Editors To The Left', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeEditorsToTheRight': { description: 'Close Editors To The Right', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.closeAllEditors': { description: 'Close All Editors', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.reopenClosedEditor': { description: 'Reopen Closed Editor', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.keepEditor': { description: 'Keep Editor', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.openNextRecentlyUsedEditorInGroup': { description: 'Open Next Editor', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.copyPathOfActiveFile': { description: 'Copy Path Of Active File', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.revealActiveFileInWindows': { description: 'Reveal Active File In Windows', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.files.showOpenedFileInNewWindow': { description: 'Show Opened File In New Window', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.files.action.compareFileWith': { description: 'Compare File With...', artifactType: logItem.ArtifactType.MenuItem },
    // displayCommands
    'workbench.action.toggleFullScreen': { description: 'Toggle Full Screen', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.toggleZenMode': { description: 'Toggle Zen Mode', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.exitZenMode': { description: 'Exit Zen Mode', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.zoomIn': { description: 'Zoom In', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.zoomOut': { description: 'Zoom Out', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.zoomReset': { description: 'Reset Zoom', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.toggleSidebarVisibility': { description: 'Toggle Sidebar Visibility', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.view.explorer': { description: 'Show Explorer', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.view.scm': { description: 'Show SCM', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.view.debug': { description: 'Show Debug', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.view.extensions': { description: 'Show Extensions', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.output.toggleOutput': { description: 'Toggle Output', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.quickOpenView': { description: 'Quick Open View', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.terminal.openNativeConsole': { description: 'Open Native Console', artifactType: logItem.ArtifactType.MenuItem },
    'markdown.showPreview': { description: 'Toggle Markdown Preview', artifactType: logItem.ArtifactType.MenuItem },
    'markdown.showPreviewToSide': { description: 'Markdown Preview To Side', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.terminal.toggleTerminal': { description: 'Toggle Terminal', artifactType: logItem.ArtifactType.MenuItem },
    // searchCommands
    'workbench.view.search': { description: 'Show Search', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.replaceInFiles': { description: 'Replace in Files', artifactType: logItem.ArtifactType.MenuItem },
    'toggleSearchCaseSensitive': { description: 'Toggle Match Case', artifactType: logItem.ArtifactType.MenuItem },
    'toggleSearchWholeWord': { description: 'Toggle Match Whole Word', artifactType: logItem.ArtifactType.MenuItem },
    'toggleSearchRegex': { description: 'Toggle Search Regex', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.search.toggleQueryDetails': { description: 'Toggle Search Details', artifactType: logItem.ArtifactType.MenuItem },
    'search.action.focusNextSearchResult': { description: 'Focus Next Search Result', artifactType: logItem.ArtifactType.MenuItem },
    'search.action.focusPreviousSearchResult': { description: 'Focus Previous Search Result', artifactType: logItem.ArtifactType.MenuItem },
    'history.showNext': { description: 'Show Next Search Term', artifactType: logItem.ArtifactType.MenuItem },
    'history.showPrevious': { description: 'Show Previous Search Term', artifactType: logItem.ArtifactType.MenuItem },
    // preferenceCommands
    'workbench.action.openSettings': { description: 'Open Settings', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.openWorkspaceSettings': { description: 'Open Workspace Settings', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.openGlobalKeybindings': { description: 'Open Keyboard Shortcuts', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.openSnippets': { description: 'Open User Snippets', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.selectTheme': { description: 'Select Color Theme', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.configureLocale': { description: 'Configure Display Language', artifactType: logItem.ArtifactType.MenuItem },
    // debugCommands
    'editor.debug.action.toggleBreakpoint': { description: 'Toggle Breakpoint', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.start': { description: 'Start Debugging', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.continue': { description: 'Continue', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.run': { description: 'Start Without Debugging', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.pause': { description: 'Pause', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.stepInto': { description: 'Step Into', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.stepOut': { description: 'Step Out', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.stepOver': { description: 'Step Over', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.debug.stop': { description: 'Stop', artifactType: logItem.ArtifactType.MenuItem },
    'editor.debug.action.showDebugHover': { description: 'Show Debug Hover', artifactType: logItem.ArtifactType.MenuItem },
    // taskCommands
    'workbench.action.tasks.build': { description: 'Run Build Task', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.action.tasks.test': { description: 'Run Test Task', artifactType: logItem.ArtifactType.MenuItem },
    // extensionCommands
    'workbench.extensions.action.installExtension': { description: 'Install Extension', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.extensions.action.showInstalledExtensions': { description: 'Show Installed Extensions', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.extensions.action.listOutdatedExtensions': { description: 'List Outdated Extensions', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.extensions.action.showRecommendedExtensions': { description: 'Show Recommended Extensions', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.extensions.action.showPopularExtensions': { description: 'Show Popular Extensions', artifactType: logItem.ArtifactType.MenuItem },
    'workbench.extensions.action.updateAllExtensions': { description: 'Update All Extensions', artifactType: logItem.ArtifactType.MenuItem }
};
